name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      # 1. Check out the student's code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install MPI and C++ compiler
      - name: Set up C++ and MPI environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential openmpi-bin libopenmpi-dev

      # 3. Compile the student's code using the Makefile
      - name: Compile C++ code
        run: make all

      # 4. Run the autograding test using the I/O grader
      - name: Random Walk Test
        id: random-walk-test
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Random Walk Test
          # Command to run 1 controller and 3 walkers
          command: "mpirun --oversubscribe -np 4 ./random_walk 20 1000"
          input: "" # This program does not use standard input
          # Check if the controller's final message is present in the output
          expected-output: "All 3 walkers have finished"
          comparison-method: contains # Use 'contains' because output is non-deterministic
          timeout: 10
          max-score: 10

      # 5. Report the results
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          RANDOM-WALK-TEST_RESULTS: "${{steps.random-walk-test.outputs.result}}"
        with:
          runners: random-walk-test